repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.13.1  # Use the latest version
    hooks:
    - id: isort
      args: ["--profile", "black"]

  - repo: https://github.com/psf/black
    rev: 23.12.0
    hooks:
    - id: black
      language_version: python3
      
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: end-of-file-fixer

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    - id: flake8
      args: ['--ignore=E501']
