version: '3.8'

services:
  postgres_db:
    image: 'postgres:14.1-alpine'
    restart: 'always'
    container_name: postgres_db
    environment:
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: '1234'
        POSTGRES_DB: 'postgres'
        log_statement: "all"
    ports:
      - '5432:5432'
  protestcrawler:
    container_name: protestcrawler
    build: "protestcrawler"
    image: ${PROTESTCRAWLER_IMAGE_BUILD:-sfarhad/protestcrawler:0.0.0}
  telegrambot:
    container_name: telegrambot
    build: "telegrambot"
    image: ${TELEGRAMBOT_IMAGE_BUILD:-sfarhad/telegrambot:0.0.0}
    ports:
      - '443:443'
    environment:
      - IP_ADDRESS=${IP_ADDRESS}
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
    volumes:
      - ./telegrambot/output:/app/output
