name: Dockerhub Publish and Deploy on host

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - '.pre-commit-config.yaml'
      - '.github/**'
      - 'docs/**'
      - 'README.md'
  workflow_dispatch:

jobs:
  build-and-push-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx with QEMU
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm64

      - name: Build and push arm64 image
        run: |
          docker buildx bake --push --file docker-compose.yml

  deploy-on-host:
    runs-on: self-hosted
    needs: [build-and-push-to-dockerhub]
    steps:
    - name: Deploy to Self-Hosted
      env:
        BRANCH: main
        CONTAINER_DIR: Action-Home/telegram-bot-protests-in-berlin
        CONTAINER_NAMES: "postgres_db protestcrawler telegrambot tor_privoxy"
        TG_BOT_TOKEN: ${{secrets.TG_BOT_TOKEN}}
        DB_UPDATE_PERIOD: ${{secrets.DB_UPDATE_PERIOD}}
        IP_ADDRESS: ${{secrets.IP_HOST}}
        SSL_PORT: ${{secrets.SSL_PORT}}
      run: |
        export TG_BOT_TOKEN=$TG_BOT_TOKEN &&
        export DB_UPDATE_PERIOD=$DB_UPDATE_PERIOD &&
        export IP_ADDRESS=$IP_ADDRESS &&
        export SSL_PORT=$SSL_PORT &&
        cd ${HOME}/$CONTAINER_DIR  &&
        git fetch --all  &&
        git rev-parse --verify --quiet $BRANCH &&
        git checkout $BRANCH  &&
        git merge origin/$BRANCH  &&
        docker compose down  &&
        docker system prune -af  &&
        cat telegrambot-entrypoint/webhook-setup.sh telegrambot-entrypoint/nginx-setup.sh | tee telegrambot/entrypoint.sh &&
        docker compose up -d  &&
        echo Check whether the docker containers are running...  &&
        for CONTAINER_NAME in $CONTAINER_NAMES; do
          if ! docker ps -q --filter name=^${CONTAINER_NAME}$ --filter status=running | grep -q .; then
            echo "Container $CONTAINER_NAME is not running."
            exit 1
          else
            echo "Container $CONTAINER_NAME is running."
          fi
        done &&
        echo All docker containers are running.
