name: Dockerhub Publish

on:
  push:
    branches:
      - main  # Set this to the branch you want to trigger the workflow
    tags:
      - 'v*'  # This will trigger the workflow for any pushed tags with the 'v' prefix

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: sfarhad/telegram-bot-protests-in-berlin:latest  # Replace with your Docker Hub username/repository
